name: Build Container Artifact

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'
        type: string

jobs:
  lint-and-build:
    uses: ./.github/workflows/lint-and-build.yml

  build-artifact:
    runs-on: ubuntu-latest
    needs: lint-and-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: starter-configs:${{ inputs.branch }}
          outputs: type=docker,dest=/tmp/starter-configs-${{ inputs.branch }}.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Compress artifact
        run: gzip /tmp/starter-configs-${{ inputs.branch }}.tar

      - name: Upload container artifact
        uses: actions/upload-artifact@v4
        with:
          name: starter-configs-container-${{ inputs.branch }}-${{ github.sha }}
          path: /tmp/starter-configs-${{ inputs.branch }}.tar.gz
          retention-days: 30
