name: Build and Push Containers

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  lint-and-build:
    uses: ./.github/workflows/lint-and-build.yml

  build-and-push:
    runs-on: ubuntu-latest
    needs: lint-and-build
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Set image name and tags
        id: image-config
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            IMAGE_NAME="ghcr.io/${{ github.repository }}-dev"
            echo "tags=${IMAGE_NAME}:${{ steps.package-version.outputs.version }},${IMAGE_NAME}:latest" >> $GITHUB_OUTPUT
          else
            IMAGE_NAME="ghcr.io/${{ github.repository }}"
            echo "tags=${IMAGE_NAME}:${{ steps.package-version.outputs.version }},${IMAGE_NAME}:latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.image-config.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
